# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('uid', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_verificated',
            field=models.BooleanField(default=False),
        ),
    ]
